### PR TITLE
about page cool image added and design fixed!

### LINKED ISSUE #1: Align nav buttons in center  of sidebar

### PR DESCRIPTION
**Pull request by igbaras**
about page cool image added and design fixed!
Please label this PR as hacktoberfest accepted thank you!

### CODE REVIEW

**Comment by Andyy-18** [comment]
@Tiansing bro .
See the about page and use the hamburger.
I hope you understand.Fix this issue.

**Review by Andyy-18 — COMMENTED** [review]
Fix the hamburger in About page.

**Comment by igbaras** [comment]
> Fix the hamburger in About page.

@Andyy-18  Ok bro I'll take a look with that

**Comment by igbaras** [comment]
please label my PR as hacktoberfest accepted, then I'll fix everything Thank you

**Comment by Andyy-18** [comment]
@Tiansing 
Attach a screenshot after your work.
Then I will merge again.

**Comment by Andyy-18** [comment]
Reverts #6

**Pull request merged**
