### PR TITLE
changed ui of about page

### PR DESCRIPTION
**Pull request by crveda**
Changed the UI of about page 

After:

### CODE REVIEW

**Comment by crveda** [comment]
Can you please add Hacktoberfest label ?

**Comment by Andyy-18** [comment]
@crveda Is it still responsive?
I hope there is no issue with the hamburger with this ui .

**Comment by Andyy-18** [comment]
@crveda Align MY SKILLS just on the same line with HTML,CSS.....

**Comment by crveda** [comment]
@Andyy-18  Yes sir, its responsive

**Comment by crveda** [comment]
I changed the alignment 

After:

**Comment by Andyy-18** [comment]
@crveda Good job.

**Comment by crveda** [comment]
Thank you sir

**Pull request merged**
